#! /bin/sh -x

########################
#####   VARIABLES  #####
########################

BORDER_WIDTH=3
BORDER_COLOR="#ff910e"
WINDOW_GAP=5
SPLIT_RATIO=0.60
PADDING_SIZE=5
BORDERLESS_MONOCLE=false
GAPLESS_MONOCLE=true
D=0
X_OFFSET=0

sxhkd &
compton &

feh --bg-scale /home/riccardo/Immagini/clouds.jpeg

# Clean up: removes istances of polybar + bspwm
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done

for monitor in $(bspc query -M --names)
do
    bspc monitor $monitor -r
done

# Start BSPWM and Polybar

bspc monitor -d 1 2 3 4 5 6 7 8 9
polybar -r main &

##########################
#####     CONFIG    ######
##########################

bspc config window_gap 		 	$WINDOW_GAP
bspc config border_width		$BORDER_WIDTH
bspc config focused_border_color	$BORDER_COLOR
bspc config split_ratio			$SPLIT_RATIO
bspc config borderless_monocle		$BORDERLESS_MONOCLE
bspc config gapless_monocle		$GAPLESS_MONOCLE

##########################
#####     RULES      #####
##########################

bspc rule -a Zathura state=tiled
for side in top right bottom left ; do
	bspc config ${side}_padding $BORDER_WIDTH
done

#redshift -l 43.94:11.47
